### ISSUE TITLE
Add support for "text/html"

### ISSUE THREAD

**Issue by mfulton26** [hansifer/TabCopy#3]
I really like this extension and I use it frequently for copying links to be used in StackOverflow and other places that accept various kinds of markup, etc. The one place where it is a bit of a pain to use is when I am composing an email, document, etc. that support rich text.

TabCopy Options supports various "text/plain" formats but what I want is "text/html" format too so that when I paste my data into a document I get "[Example Domain](http://www.example.com/)" instead of "\[Example Domain](http://<span/>www.example.com/)".

This can be done by setting additional clipboard data in addition to the plain text:

```JavaScript
function copy(text, url) {
  document.oncopy = function(event) {
    event.clipboardData.setData('text/plain', text);
    event.clipboardData.setData('text/html', '<a href="' + url + '">' + text + '</a>');
    event.preventDefault();
  };
  document.execCommand('copy');
}

copy('http://www.example.com/', 'Example Domain')
```

Here's a live demo: https://jsfiddle.net/L40a2h4s/3/

Can support for this be added?

Thanks.

**Comment by hansifer** [comment]
Thanks for the suggestion, Mark.

I actually have this implemented already in the next version, which I need
to put some finishing touches on before I release. Hoping to find the
bandwidth for this within the next couple of weeks.

If you don't see the new release within 2 weeks give me a nudge and I'll
reprioritize my workload accordingly if I can.

Thanks,
Hans

**Comment by mfulton26** [comment]
Awesome! I look forward to the update!

**Comment by mfulton26** [comment]
> If you don't see the new release within 2 weeks give me a nudge and I'll
reprioritize my workload accordingly if I can.

19 days and counting. I'm looking forward to the new release and hoping you'll have time soon. Thanks!

**Comment by hansifer** [comment]
Ah yes. Thanks for the reminder :)

I will make time this weekend to wrap up the release. Thanks for your
patience.

Hans

**Comment by hansifer** [comment]
v3.1 has been deployed to the Chrome Web Store. Let me know if it suits your needs.

**Comment by mfulton26** [comment]
Yep. That is awesome. Thank you!
